---
# defaults file for common
# 1. Lists of Necessary Packages
common_prereq_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg

# 2. Lists of K8s Core Components
common_k8s_packages:
  - cri-o
  - kubelet
  - kubeadm
  - kubectl

# 3. K8s Ops & NW/NFS System Dependencies
common_k8s_dependencies:
  - conntrack
  - ebtables
  - ethtool
  - iptables
  - socat
  - nfs-common
  - python3-kubernetes
  - python3-yaml  

# 4. Repository Default URL
crio_repo_base_url: "https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/deb"
k8s_repo_base_url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb"
