---
# tasks file for argocd-core
- name: Create ArgoCD Namespace (Ensure Idempotency)
  ansible.builtin.shell: >
    kubectl create namespace {{ argocd_namespace }} --dry-run=client -o yaml | kubectl apply -f -
  register: ns_create
  changed_when: "'created' in ns_create.stdout"

- name: Deploy Lightweight ArgoCD Core
  ansible.builtin.shell: >
    kubectl apply -n {{ argocd_namespace }} --server-side -force-conflicts -f 
    https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version }}/manifests/core-install.yaml
  register: deploy_result
  changed_when: "'created' in deploy_result.stdout or 'configured' in deploy_result.stdout or 'server-side apply' in deploy_result.stdout"

- name: Ensure Running State of ArgoCD Core Pod
  ansible.builtin.shell: >
    kubectl wait --for=condition=ready pod --all -n {{ argocd_namespace }} --timeout=300s
  register: pod_status
  changed_when: false
