---
# Tasks for ArgoCD Core Deployment
- name: "[1] Lightweight ArgoCD Core Deployment"
  hosts: master
  become: true
  roles:
    - argocd-core

- name: "[2] ArgoCD CLI Optimization"
  hosts: localhost
  connection: local
  roles:
    - argocd-cli
