---
# tasks file for worker
# Cluster Join via Join Command from Master node
- name: Join worker nodes to the cluster
  shell: "{{ extracted_join_cmd }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
